FROM node:18
WORKDIR /web

# install dependencies into temp directory
# this will cache them and speed up future builds

COPY ./web/package.json ./

ENV BODY_SIZE_LIMIT=Infinity

RUN npm install

COPY ./web ./

RUN npm run build

# run the app
USER root
EXPOSE 3000
ENTRYPOINT [ "node", "build"]