import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';

const serviceAccountAuth = new JWT({
	// env var values here are copied from service account credentials generated by google
	// see "Authentication" section in docs for more info
	email: process.env.CLIENT_EMAIL,
	key:
		process.env.NODE_ENV === 'development'
			? process.env.PRIVATE_KEY
			: process.env.PRIVATE_KEY?.split(String.raw`\n`).join('\n'),
	scopes: ['https://www.googleapis.com/auth/spreadsheets']
});

export const doc = new GoogleSpreadsheet(
	'1_6oScm5DaGq53lEFkhOfzmq5Z0GbJ2_SheZyajqDLl0',
	serviceAccountAuth
);

await doc.loadInfo();

export const sheet = doc.sheetsByIndex[0];

export async function getTag(discordid: string) {
	await sheet.loadCells();
	for (let i = 3; i < sheet.rowCount; i++) {
		const cell = sheet.getCell(i, 0);
		if (cell.note) {
			if (cell.note.split('\n')[0] === discordid) {
				return {
					name: cell.value,
					discordid: cell.note.split('\n')[0],
					rang: cell.note.split('\n')[1] ? cell.note.split('\n')[1] : 'tag'
				};
			}
		}
	}
}
