//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

pub mod hailes;
pub mod logs;
pub mod service_bills;
pub mod shorts;
pub mod statuses;
pub mod supplement_types;
pub mod supplements;
pub mod types;
