import 'dotenv/config';

import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';

const serviceAccountAuth = new JWT({
	// env var values here are copied from service account credentials generated by google
	// see "Authentication" section in docs for more info
	email: process.env.CLIENT_EMAIL,
	key: process.env.NODE_DEV
		? process.env.PRIVATE_KEY
		: process.env.PRIVATE_KEY?.split(String.raw`\n`).join('\n'),
	scopes: ['https://www.googleapis.com/auth/spreadsheets']
});

export const doc = new GoogleSpreadsheet(
	'1_6oScm5DaGq53lEFkhOfzmq5Z0GbJ2_SheZyajqDLl0',
	serviceAccountAuth
);

await doc.loadInfo();

export const sheet = doc.sheetsByIndex[0];

const rowes = (await loadRowes()) as number;

async function loadRowes() {
	await sheet.loadCells();
	for (let i = 1; i < sheet.rowCount; i++) {
		const cell = sheet.getCellByA1(`A${i}`);
		if (cell.value === 'Összesen') {
			return i - 1;
		}
	}
}

export async function getTag(discordid: string) {
	await sheet.loadCells(`A3:A${rowes}`);
	for (let i = 4; i < rowes; i++) {
		const cell = sheet.getCellByA1(`A${i}`);
		if (cell.note) {
			if (cell.note.split('\n')[0] === discordid) {
				return {
					name: cell.value,
					discordid: cell.note.split('\n')[0],
					rang: cell.note.split('\n')[1] ? cell.note.split('\n')[1] : 'tag',
					row: i
				};
			}
		}
	}
}
